import { IIssueType } from './issue-type';
import { IAssetIssueCategoryType } from './asset-issue-category-type';
import { ITaggingKeyword } from '../../assets/tagging-keyword';
import { IAssetInfo } from '../../assets/asset-info';
import { IIssueCauseType } from './issue-cause-type';
import { IAssetIssueAssetIssueImpactTypeMap } from './asset-issue-asset-issue-impact-type-map';

export interface IAssetIssue {
  AssetIssueID: number;
  AssetID: number;
  IssueType: IIssueType;
  IssueTypeID: number;
  AssetIssueCategoryType: IAssetIssueCategoryType;
  AssetIssueCategoryTypeID: number;
  ActivityStatus: string;
  ActivityStatusID: number;
  ResolutionStatus: string;
  ResolutionStatusID: number;
  IssueCauseTypeID: number;
  Priority: string;
  Action: string;
  CreateDate: Date;
  ChangeDate: Date;
  CreatedBy: string;
  ChangedBy: string;
  Confidence_Pct: number;
  Risk: number;
  ModelConditionID: number;
  IssueTitle: string;
  IssueSummary: string;
  CloseDate: Date;
  OpenDate: Date;
  OpenDuration: number;
  LastEmailSent: Date;
  CreatedByUserID: number;
  AssetAndParents: IAssetInfo;
  CategoryDesc: string;
  IssueTypeDesc: string;
  IssueCauseType: IIssueCauseType;
  ImpactMaps: IAssetIssueAssetIssueImpactTypeMap[];
  ImpactsString: string;
  BlogID: string;
  RelatedIssues: number[];
  ActionPlans: any[];
  CausalFactors: any[];
  IssueCauseTypes: IIssueCauseType[];
  GlobalID: string;
  CanEdit: boolean;
  CanDelete: boolean;
  CanEditIssueStatus: boolean;
  IssueShortSummary: string;
  Scorecard: boolean;
  AssignedTo: string;
  NERCCIP?: boolean;
  Keywords: ITaggingKeyword[];
  ResolveBy?: Date;
  editableSummary?: string;
  safeHtmlIssueSummary?: string;
  editingIssueSummary?: boolean;
}
